
name: Android CI (FinQwerty)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Setup Android SDK (optional but recommended)
        uses: android-actions/setup-android@v3
        with:
          packages: ''

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Debug (finqwerty)
        run: ./gradlew :finqwerty:clean :finqwerty:assembleDebug --stacktrace

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: finqwerty-debug-apk
          path: |
            finqwerty/build/outputs/apk/debug/*.apk
            finqwerty/build/outputs/apk/**/*.apk
          if-no-files-found: error

